#server.port=8080

# profiles = y的专用属性，用于指定使用哪个配置文件，默认为default
#spring:
#  profiles:
#    active: prod

spring:
    devtools:
        restart:
            enabled: true #设置开启热部署
            additional-paths: src/main/java #重启目录
            exclude: WEB-INF/**
    freemarker:
        cache: false  #页面不加载缓存，修改即时生效
